### ISSUE TITLE
BUG: Fix the CSS of Let's get started section in development page

### ISSUE THREAD

**Issue by KeyurGK** [dakshsinghrathore/Brighter-Beginnings#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- The Let's Get Started section on the development page has a broken UI: https://brighter-beginnings.vercel.app/development.html
<img width="957" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/56074740/be9af70a-cc90-4755-809d-61abead326eb">
- The same section has a smooth UI on other pages like Problem Solving and Logic pages.
<img width="960" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/56074740/ade3295f-855c-4bfb-8273-ed52352c1468">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by KeyurGK** [comment]
@dakshsinghrathore Looking forward to getting assigned and contribute!

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @KeyurGK , kindly drop a star on this repo 
HAPPY CODING !
