### ISSUE TITLE
BUG: Alignment Issue

### ISSUE THREAD

**Issue by sherabhai** [dakshsinghrathore/Brighter-Beginnings#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @dakshsinghrathore 

I came across your website, and found this Let's Get Started Button has been a little bugged, would take care of it for you. If you can assign me the issue! 

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/156661163/488a394d-973b-472b-afc1-d2cdff7e7201)

Best Regards,
**Shera Bhai**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by KeyurGK** [comment]
Hey @sherabhai Already fixing it in #102
