### ISSUE TITLE
Feat: Implement PR Title Checker workflow for Conventional Commit Prefixes 

### ISSUE THREAD

**Issue by harmeetsingh11** [dakshsinghrathore/Brighter-Beginnings#109]
**Description:**
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

**Proposed Changes:**
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Expected Behavior:**
When contributors create new PRs or issues, the GitHub Action should automatically trigger and post a welcoming message, acknowledging their contributions.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@harmeetsingh11 Thanks for creating the issue, but this feature is already implemented.
