### ISSUE TITLE
Feat: About Page

### ISSUE THREAD

**Issue by kom-senapati** [dakshsinghrathore/Brighter-Beginnings#11]
### Describe the feature

About page missing

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/0cc3cb42-0b23-4a5c-a54f-cf79963d3a38)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by qutequbit** [comment]
I would like to contribute to the About Page.

**Comment by dakshsinghrathore** [comment]
Hey @kom-senapati do share the design ideas you would like to implement and lets see if we want the changes or not, kindly share the figma link of the proposed design for this page.
Happy Coding !

**Comment by kom-senapati** [comment]
Let's discuss at discord about this and then I will try to make one.
