### ISSUE TITLE
Feat:Add the hover effects  for images on the get started page

### ISSUE THREAD

**Issue by Prutha-Upadhyay** [dakshsinghrathore/Brighter-Beginnings#111]
### Describe the feature

@dakshsinghrathore I want to add the hover effects for images on the get started page to make it attractive!!

### Add ScreenShots

Like This....!!

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/120392487/0b9dc5c2-c15b-49ac-8fa0-26ce164d724a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Tanishka023** [comment]
Hey @dakshsinghrathore can you please assign this issue to me??

**Comment by dakshsinghrathore** [comment]
@Tanishka023 we as project admins have been instructed to assign issue on first come first serve basis, kindly create new issues to work on or wait for a while will be creating beginner friendly issues soon.

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Prutha-Upadhyay , kindly drop a star on this repo 
HAPPY CODING !

**Comment by Tanishka023** [comment]
> @Tanishka023 we as project admins have been instructed to assign issue on first come first serve basis, kindly create new issues to work on or wait for a while will be creating beginner friendly issues soon.

Okay! @dakshsinghrathore
