### ISSUE TITLE
Fixing Typo Error

### ISSUE THREAD

**Issue by GhoshAditi** [dakshsinghrathore/Brighter-Beginnings#113]
![bug](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/144611267/c8f3f5ab-9761-4f80-9f08-7281350f40ce)
The mentioned text will be problem 4 instead og problem 3. I would like to fix this typo error.

**Comment by GhoshAditi** [comment]
@dakshsinghrathore plz assign it to me under swoc'24.

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @GhoshAditi , kindly drop a star on this repo 
HAPPY CODING !
