### ISSUE TITLE
to add eye icon in password.

### ISSUE THREAD

**Issue by Sanjana787** [dakshsinghrathore/Brighter-Beginnings#115]
### Describe the feature

Add an eye icon in the password to view the entered password.

### Add ScreenShots

![6](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/141259407/7b0805e7-3e9c-4751-96d8-e2208e908530)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Sanjana787 , kindly drop a star on this repo 
HAPPY CODING !

**Comment by gayathrik23** [comment]
@dakshsinghrathore  can u assign this issue to me... I am interested in contributing to this project under swoc
