### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by Sanjana787** [dakshsinghrathore/Brighter-Beginnings#116]
![6](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/141259407/673a1f8d-798b-4aa1-b99d-f2bbe8f42fe6)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the user registration form, numeric values are also accepted however it should accept only characters and spaces.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Manishkr1007** [comment]
assign me this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Sanjana787 , kindly drop a star on this repo 
HAPPY CODING !

**Comment by Nandini80** [comment]
@dakshsinghrathore, if this task hasn't been completed yet, kindly assign it to me.
