### ISSUE TITLE
DARK MODE 

### ISSUE THREAD

**Issue by student-aditipaliwal** [dakshsinghrathore/Brighter-Beginnings#117]
### Describe the feature

can add darkmode option in right most corner .

### Add ScreenShots

![Screenshot 2024-01-19 191530](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/147225647/8fa6fe34-a399-4b24-82da-e952c6f24539)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Manishkr1007** [comment]
allow  me to contribute @student-aditipaliwal

**Comment by Shivam250702** [comment]
allow me to contribute @student-aditipaliwal
