### ISSUE TITLE
BUG: Extra Logo at the bottom 

### ISSUE THREAD

**Issue by SurajPratap10** [dakshsinghrathore/Brighter-Beginnings#118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- Since the Navbar is sticky and has it's own logo, so as we scroll down to the bottom of the website we encounter 2 logos which leaves a bad impression on the ui of the website. So, the bottom logo should be removed.

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92919173/a8fb524e-48d3-4aa1-a3f3-93d3244b2fd3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Nandini80** [comment]
@dakshsinghrathore  If not done please assign this to me.

**Comment by Nandini80** [comment]
@dakshsinghrathore Please reply

**Comment by dakshsinghrathore** [comment]
Its already fixed
