### ISSUE TITLE
Feat: ADDING SEARCH BAR 

### ISSUE THREAD

**Issue by mansi1309** [dakshsinghrathore/Brighter-Beginnings#119]
### Describe the feature

I would like to add search bar in header section in nav bar ,so that every one can search any thing.

### Add ScreenShots

I would like to add something like that
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/133951716/47e771b9-2b99-4d54-bd2a-30df6c0b599b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Gungun2310** [comment]
hey @mansi1309 kindly assign this issue to me.
