### ISSUE TITLE
Chore: Better folder structure

### ISSUE THREAD

**Issue by kom-senapati** [dakshsinghrathore/Brighter-Beginnings#12]
### Describe the chore

This folder structure is confusing. It can be improved by making folders like assets/css (for custom css), assets/js (for js logic), pages (for html files excluding index.html and 404.html.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/32c97712-a22e-4b18-aa12-0b5f6fb6f701)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@kom-senapati Sound good, go ahead....... assigning it to you .
