### ISSUE TITLE
Feat: Addition of new module [Advance Module] 

### ISSUE THREAD

**Issue by Parth4git** [dakshsinghrathore/Brighter-Beginnings#126]
### Describe the feature

Advance module provide  resources to learn Tensorflow ,numpy libraries and AI  ,which is necessary for user to have complete resources at once place [Brighter-Beginnings]

### Add ScreenShots

![Screenshot 2024-01-21 162406](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/99666524/b0375bf4-c2ca-4f97-9cac-f2009c3cd600)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Parth4git** [comment]
@dakshsinghrathore  
kindly reply to my issue .Can I work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Parth4git , kindly drop a star on this repo 
HAPPY CODING !

**Comment by Parth4git** [comment]
@dakshsinghrathore take a look on UI . So I can make PR

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/99666524/aadaa0d6-2ebc-4fbd-8a63-0672e5a34b6a

**Comment by dakshsinghrathore** [comment]
Have you made it responsive ??.

**Comment by Parth4git** [comment]
yes

**Comment by dakshsinghrathore** [comment]
@Parth4git good to go, create the PR

**Comment by Parth4git** [comment]
@dakshsinghrathore kindly review my PR
