### ISSUE TITLE
Feat: Add icon on Home and Feedback button

### ISSUE THREAD

**Issue by Ishita928** [dakshsinghrathore/Brighter-Beginnings#127]
### Describe the feature

A relevant icon can be added on home and feedback button at the side of its text to make it look more appealing

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/146575485/de99cd58-6c2d-43e1-93af-906c8596b57d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Ishita928  , kindly drop a star on this repo 
HAPPY CODING !
