### ISSUE TITLE
Feat: Blog Page

### ISSUE THREAD

**Issue by kom-senapati** [dakshsinghrathore/Brighter-Beginnings#13]
### Describe the feature

There is no blog page. If it's intended for custom blogs, then a mini blog application can be made here else external blog links can be added topic-wise.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/a686816b-877b-4aa7-b0a9-6550963d658b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Hey @kom-senapati do share the design ideas you would like to implement and lets see if we want the changes or not, kindly share the figma link of the proposed design for this page.
Happy Coding !

**Comment by kom-senapati** [comment]
I don't have any ideas currently. I mentioned two ways in which you can use this page. Think about that and share how you want to populate this page.

**Comment by Shreyas-SAS** [comment]
If @kom-senapati isn't working on it, Can I produce some design solutions for the blog page @dakshsinghrathore?

**Comment by kom-senapati** [comment]
@Shreyas-SAS What are you planning on micro-blog app or blog links?

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS What are you planning on micro-blog app or blog links?

Blog links from a reputed blogging site curated for a particular topic. 

Currently we do not have either the audience to self create that amount of content neither from the repo owners site. 

I was thinking something on the lines of fetching articles from hashnode and medium related to each Programming language and then user can select which one he wishes to read.

**Comment by Shreyas-SAS** [comment]
> > @Shreyas-SAS What are you planning on micro-blog app or blog links?
> 
> Currently we do not have either the audience to self create that amount of content neither from the repo owners site. 

Apart from this, we could maybe have a link for users to submit a link to their own blog pages and me might display then in a student blogs section I guess.

**Comment by kom-senapati** [comment]
Awesome ideas! You can take up this issue.

**Comment by Shreyas-SAS** [comment]
@dakshsinghrathore please assign me this issue whenever you are free. will start working on this as well.

Thanks,
Shreyas

**Comment by dakshsinghrathore** [comment]
@Shreyas-SAS any updates ??

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS any updates ??

Yes, facing a bit of issue with incorporating articles from both Hashnode and medium together. 

Will put a PR as soon as I resolve them.

**Comment by harshsinghcs** [comment]
@Shreyas-SAS you are working on this issue. If  you don't mind I'll help you.

**Comment by Shaba1406** [comment]
@Shreyas-SAS Hey
How your work is going on , Any updates

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS Hey
> How your work is going on , Any updates 

Really sorry! Was stuck with some academic work so couldn't give a lot of time. It's the 3rd issue on my todos at the moment. Will work on it most probably on monday and put a PR asap if it's ok. In case of urgency please feel free to direct me to drop the work, I am ok with assigning others with this issue as well. 

Past work:
Had completed the interface but problem with fetching from multiple sources so will only fetch from hashnode. 

Note:
Will be dropping the student's blogs additional part given that it will be difficult to implement with requirement of database and API creation. In short too ambitious for the project at the moment.

**Comment by Shreyas-SAS** [comment]
> > @Shreyas-SAS Hey
> > How your work is going on , Any updates 
> 
> Really sorry! Was stuck with some academic work so couldn't give a lot of time. It's the 3rd issue on my todos at the moment. Will work on it most probably on monday and put a PR asap if it's ok. In case of urgency please feel free to direct me to drop the work, I am ok with assigning others with this issue as well. 
> 
> Past work:
> Had completed the interface but problem with fetching from multiple sources so will only fetch from hashnode. 
> 
> Note:
> Will be dropping the student's blogs additional part given that it will be difficult to implement with requirement of database and API creation. In short too ambitious for the project at the moment.

Ps: a bit of work on responsive design is also remaining.

**Comment by Shaba1406** [comment]
yeah take your time but keep us updating

**Comment by Shreyas-SAS** [comment]
hey @Shaba1406 I think I will not be able to complete this issue, can you please float it as up for grabs? Sorry!

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS you are working on this issue. If you don't mind I'll help you.

If you are still interested, please do pick the issue up.
