### ISSUE TITLE
BUG: Fix Footer and about page color discrepancy

### ISSUE THREAD

**Issue by anirbanmajumder0** [dakshsinghrathore/Brighter-Beginnings#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The about page and the logic footer white color is too jarring to the eye change it to a neutral shade of white will be better. 

This footer has the best white color.
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/81350357/bac0ba57-5b69-4dec-9210-54bc445dc9e4)

This footer is just pure **Eye Strain.**
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/81350357/91bd2a07-38b7-46f7-9848-967015ffbdfb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigning it to you @anirbanmajumder0 kindly drop a star on this repo
Happy Coding
