### ISSUE TITLE
The feature 'Validations' is currently missing on the registration page.

### ISSUE THREAD

**Issue by Niharika0104** [dakshsinghrathore/Brighter-Beginnings#134]
### Describe the feature

The desired feature involves implementing validations on the registration page, enhancing the user experience by ensuring that user input adheres to specified criteria and providing informative feedback. This addition aims to improve data accuracy and guide users through the registration process with clarity, ultimately contributing to a smoother and more user-friendly interaction.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/124892559/f4c11dac-8611-4582-9d96-1ef2ea043f86)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Niharika0104 , kindly drop a star on this repo 
HAPPY CODING !
