### ISSUE TITLE
feat:Enhance Newsletter Subscription with Validations and Confirmation

### ISSUE THREAD

**Issue by Niharika0104** [dakshsinghrathore/Brighter-Beginnings#136]
### Describe the feature

The current state of the Newsletter feature lacks necessary validations and confirmation, leaving room for improvement. This issue proposes to implement enhancements that ensure proper validation checks during subscription and provide users with a confirmation (like a pop-up on the screen that they are subscribed)

### Add ScreenShots

As of now,when the user is clicking on the subscribe without entering anything it is causing the whole page to refresh.
<img width="748" alt="newletter" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/124892559/a54c6826-c2f8-43e5-80de-8819d51de568">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Niharika0104** [comment]
Hey @dakshsinghrathore when I'm trying to push code ,it says ""Permission to dakshsinghrathore/Brighter-Beginnings denied to Niharika0104.The requested Url returned 403"".Can you please confirm is this an issue from your end or my end.Yesterday,I was very well able to make PR.

**Comment by dakshsinghrathore** [comment]
@Niharika0104 will update you by tonight regarding this.
