### ISSUE TITLE
BUG: Register page not clear

### ISSUE THREAD

**Issue by kom-senapati** [dakshsinghrathore/Brighter-Beginnings#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The page lacks appeal as the colorful background contrasts with white text.

I want to present this as a card with a glassmorphic effect for improved text clarity.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Shaba1406** [comment]
Could you share the images as well

**Comment by kom-senapati** [comment]
> Could you share the images as well

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92045934/4f36b4c6-5f92-4323-a638-a8b02beabc40)
