### ISSUE TITLE
Feat: UI Enhancement!

### ISSUE THREAD

**Issue by mohitparmar1** [dakshsinghrathore/Brighter-Beginnings#143]
### Describe the feature

Logic , problem solving , development should have logo and proper shadow something!

### Add ScreenShots

![Screenshot 2024-01-28 233321](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/100152343/d431a94d-76b2-470f-a338-8df0f5636efd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @mohitparmar1 , kindly drop a star on this repo 
HAPPY CODING !

**Comment by dakshsinghrathore** [comment]
@mohitparmar1 any updates ??

**Comment by mohitparmar1** [comment]
some one already completed this!
