### ISSUE TITLE
Horizontal Scroll Bar

### ISSUE THREAD

**Issue by Nandini80** [dakshsinghrathore/Brighter-Beginnings#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Horizontal Scroll Bar on About us page.

<img width="960" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/121488571/7b55bc09-d53b-431c-ba98-597ca556f48e">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Nandini80 
HAPPY CODING !
