### ISSUE TITLE
Add Animate-on-Scroll feature 

### ISSUE THREAD

**Issue by Devanshe15** [dakshsinghrathore/Brighter-Beginnings#149]
### Describe the feature

"Animate-on-Scroll" feature to the first page of our website to enhance user engagement and provide a more dynamic user experience.

**Type of Animation**:  Implement animations that trigger as users scroll up or down on the first page.

**Desired Effects**:  fade-ins, slide-ups, scale effects.
## Purpose and Benefits
The purpose of this feature is to make the first page more engaging and visually appealing. Animated elements that appear as users scroll can capture attention and create a more memorable experience.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/66192225/c2a9f2b4-ff02-4e2e-b7b2-f751d36963aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @Devanshe15 , kindly drop a star on this repo 
HAPPY CODING !
