### ISSUE TITLE
Feat: Addin GSAP Animations to the website

### ISSUE THREAD

**Issue by JATIN0926** [dakshsinghrathore/Brighter-Beginnings#157]
### Describe the feature

I want to add some minimilistic or you can say cool animations , which will make the website attractive , you can refer to my this project :

https://elitecricketacademy.netlify.app/

### Add ScreenShots

I have attached a small recording , you can refer above link for whole website

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/124780421/0ae30360-3888-4fbf-a689-51de47d32c12

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @JATIN0926 , kindly drop a star on this repo 
HAPPY CODING !

**Comment by dakshsinghrathore** [comment]
@JATIN0926  any updates ??

**Comment by dakshsinghrathore** [comment]
@JATIN0926 so you won't be working on this issue ?
