### ISSUE TITLE
BUG: Page is Horizontally Scrollable

### ISSUE THREAD

**Issue by itsmeabhishek03** [dakshsinghrathore/Brighter-Beginnings#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Page is Horizontally Scrollable which is bad user expierence i can fix it. Below is Sceenshot of Bug - 

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/104294494/5f9c0a53-eb63-4f58-82c4-107bd24d77d8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by PRITISH212121** [comment]
heyyy @itsmeabhishek03  i m interested in solving thiss!

**Comment by dakshsinghrathore** [comment]
@itsmeabhishek03 sounds good, assigning it to you.
Happy Coding !

**Comment by kom-senapati** [comment]
If its not completed, I can work on this issue.

**Comment by Shaba1406** [comment]
@itsmeabhishek03 Hey, how is the work going on ? What's the update ?

**Comment by siwamsingh** [comment]
@itsmeabhishek03 in how much time can you solve this bug .

**Comment by Nandini80** [comment]
@dakshsinghrathore If not completed can you please assign this issue to me

**Comment by Shaba1406** [comment]
@Nandini80 hey, how your work is going on 
Any Updates ??

**Comment by Nandini80** [comment]
@Shaba1406 Created a pull request. Please check.
