### ISSUE TITLE
BUG:Services page isn't working

### ISSUE THREAD

**Issue by Ashwin145** [dakshsinghrathore/Brighter-Beginnings#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (2)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/89822123/9c9329f1-b638-444e-9252-a1a165f1ed44)

Can you please specify what kind of services you are willing to provide?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by Ashwin145** [comment]
@dakshsinghrathore ??

**Comment by dakshsinghrathore** [comment]
@Ashwin145 go ahead and suggest what would you like to see in that page, based on that will apply label of difficulty. 
HAPPY CODING.

**Comment by Ashwin145** [comment]
@dakshsinghrathore Shall i close this issue?

**Comment by Ashwin145** [comment]
@dakshsinghrathore Shall i close this issue?
