### ISSUE TITLE
BUG: Logo icon is not present on top

### ISSUE THREAD

**Issue by itsmeabhishek03** [dakshsinghrathore/Brighter-Beginnings#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 Logo icon is not present on top of tab as you can see in below Screenshot - 

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/104294494/0df7d14b-5577-4aaa-b367-c34be23e3efa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by PRITISH212121** [comment]
heyyy @itsmeabhishek03 , I'm interested in solving this issue.

**Comment by Ankitapanda25** [comment]
hello @itsmeabhishek03, could you assign me this issue? I could work on it.

**Comment by Tymnspayce** [comment]
## Hey @itsmeabhishek03 , I have fixed this issue and created a PR for this.

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/138722584/a904faf3-3f57-4c28-9cfa-92eb2dbe2c7d)

**Comment by itsmeabhishek03** [comment]
@Tymnspayce I think it is not allowed! please raise your PR only if you are assigned to that issue i request you to take back your PR and wait for admin reply. Thank you

**Comment by LowkeyDone** [comment]
plz assign this issue to me

**Comment by gayathrik23** [comment]
could you please assign this to me...
