### ISSUE TITLE
Feat: Enhance Registration Page Design

### ISSUE THREAD

**Issue by Yatin12527** [dakshsinghrathore/Brighter-Beginnings#18]
### Describe the feature

The current register page design is functional, but I believe we can enhance it to provide a more aesthetically pleasing and user-friendly experience. I'm willing to contribute by redesigning the register page to align with modern design principles and improve overall user engagement.
I can fix the background of this page and incorporate background image and make the page look more aesthetically pleasing.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/5687e156-59cc-404c-80cb-c67d45abd0f4)

Here's a sample of what i can incorporate in this page 
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/83f01cbf-6e35-483a-a1f6-037dc3363574)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@Yatin12527 Seems good, kindly maintain the font-style of this page which is "Grotesk", and I hope you already know to setup TailwindCSS for this project, if not feel free to reach out to me on discord.
Happy Coding !

**Comment by Yatin12527** [comment]
> @Yatin12527 Seems good, kindly maintain the font-style of this page which is "Grotesk", and I hope you already know to setup TailwindCSS for this project, if not feel free to reach out to me on discord. Happy Coding !

Can i get your discord id?

**Comment by dakshsinghrathore** [comment]
Sure @Yatin12527  its dakshsinghrathore
