### ISSUE TITLE
Feat: Custom Hover and Active Effects for Header Sections

### ISSUE THREAD

**Issue by Yatin12527** [dakshsinghrathore/Brighter-Beginnings#19]
### Describe the feature

The current hover and active effects on the header sections are functional, but I believe introducing better effects will empower users to align the website's design . I have created a sample video demonstrating the proposed feature through my portfolio.

**Pexisting style**

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/24ed4646-7e0a-47c8-a37a-1607183acead

**Proposed style**

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/aac200f7-9e84-45f4-a736-908969b0c846

### Add ScreenShots

Portion concerned
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/037c5456-05fd-470a-80c0-544b1a636839)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by PRITISH212121** [comment]
heyy @Yatin12527  I'm intersted in solving this issue,I have worked with hoverss a lot,if you want u can take a look at my repositories i have projects which have similar hover function

**Comment by dakshsinghrathore** [comment]
Hey @Yatin12527 thanks for creating the issue, I would like to give @PRITISH212121 the opportunity to fix this, for now you can carry on with the registration page, will create bunch of more issues by tonight, you can look into them fs.

**Comment by PRITISH212121** [comment]
thanku for assigning,on it
@dakshsinghrathore
