### ISSUE TITLE
Add Favicon and Open Graph Protocols and twitter tags for efficient social media sharing.

### ISSUE THREAD

**Issue by rakesh-vajrapu** [dakshsinghrathore/Brighter-Beginnings#20]
### Describe the feature

I want to add Favicon, Open graph protocols and twitter tags for the website for efficient social media sharing. Please assign this issue to me @dakshsinghrathore 

### Add ScreenShots

![Screenshot (62)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/150238750/29e68693-c973-4971-b1b9-7a19df789a1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Sure @rakesh-vajrapu assigning it to you, kindly follow the design principle while implementing it.
HAPPY CODING !
