### ISSUE TITLE
BUG: Social media icons in the footer section are not redirecting to their respective sites

### ISSUE THREAD

**Issue by Vaishu03** [dakshsinghrathore/Brighter-Beginnings#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Whenever we click the social media icons in the footer section of the page, they are taking us to the same website again, inspite of redirecting to the respective social media accounts. 

I would like to work on this issue as a SWOC24 contributor, so @dakshsinghrathore kindly assign this task to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by PRITISH212121** [comment]
hey @Vaishu03  I would like to work on this issue

**Comment by Yuvraj960** [comment]
hey @Vaishu03 I would like to work on this issue

**Comment by dakshsinghrathore** [comment]
@Vaishu03 There are no social media handles for them as for now. So omit this issue
