### ISSUE TITLE
Designing getstarted.html page

### ISSUE THREAD

**Issue by yashi-15** [dakshsinghrathore/Brighter-Beginnings#23]
### Describe the feature

I want to add better styling to the getstarted.html page like adding appealing hover effects on the three cards present on the page and changing the styling of the items on header for a better look of the website. 
Please assign this issue to me under SWOC.

### Add ScreenShots

![Screenshot (187)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/132138302/ed88b505-842f-4b41-985b-5495b63e9ca6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by PRITISH212121** [comment]
hey @yashi-15  i have worked with hover effects a lot,I would like to contirbute

**Comment by dakshsinghrathore** [comment]
Assigned @yashi-15 ✅️
Happy Coding !

**Comment by gayathrik23** [comment]
can you assign this to me, i would like to work  on it

**Comment by dakshsinghrathore** [comment]
@gayathrik23 Thanks for showing interest in this issue, unfortunately this issue is already assigned to yashi, explore other issues or if you find some bug/features in brighterbeginnings go ahead and create a fresh one yourself, also do drop a star on this repo
HAPPY CODING !

**Comment by kom-senapati** [comment]
If the issue persists, I would like to work on it.

**Comment by dakshsinghrathore** [comment]
@kom-senapati kindly go ahead and fix the issue in the getstarted page, for some reason they aren't displaying the respective images, so fix it.
