### ISSUE TITLE
Feat:  Enhancement Request: Include Required Fields in Registration Page

### ISSUE THREAD

**Issue by sagarbee** [dakshsinghrathore/Brighter-Beginnings#25]
### Describe the feature

I would like to propose an enhancement to the registration page to improve user experience and ensure essential information is captured during the registration process.

### Add ScreenShots

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/65588552/03dcb371-ce6e-412a-b958-6f6a335aeb04

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by sagarbee** [comment]
Sorry, i thought this issue was assign to me when i saw bot message of github and pull request. if possible please guide me further what to do

**Comment by Ishaparte** [comment]
Hello @sagarbee  I would like to work on this issue. Can you please assign it to me.

**Comment by dakshsinghrathore** [comment]
@sagarbee @Ishaparte this issue is already assigned to another folk, kindly create a new issue or wait for me to create couple of them and then get assigned .
Happy coding !
