### ISSUE TITLE
Adding small description about the games in logic building section

### ISSUE THREAD

**Issue by ivanMehvish** [dakshsinghrathore/Brighter-Beginnings#26]
### Describe the feature

Addition of one or two lines of description about the game

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/87938552/5e4a4b05-9284-4660-9e25-47c9dfdfe4a2)

In this page, below the heading, description can be added

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Ishaparte** [comment]
hello @ivanMehvish I would like to work on this issue. Can you please assign it to me.

**Comment by dakshsinghrathore** [comment]
Assigned ✅️
Happy Coding !
