### ISSUE TITLE
Feat:password and confirm password should be same

### ISSUE THREAD

**Issue by sagarbee** [dakshsinghrathore/Brighter-Beginnings#29]
### Describe the feature

password and confirm password should be same otherwise it should give us alert

### Add ScreenShots

![Screenshot (137)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/65588552/e40cd767-817d-4ff6-bd0a-1dd2d17d8472)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by sumanjeet0012** [comment]
I want to work on this issue.
assign it to me .

**Comment by sagarbee** [comment]
Please assign me this issue
