### ISSUE TITLE
Adding Responsiveness for all devices 

### ISSUE THREAD

**Issue by Akshanshkaushal** [dakshsinghrathore/Brighter-Beginnings#3]
Identifying a responsiveness glitch, I propose resolving it through the implementation of an overflow condition. With your approval, I'm eager to take ownership of this task as part of the SWOC'24 initiative, ensuring seamless functionality and an optimal user experience.
In addition to it a better scroll bar can be added , enhancing its visual appearance.
![resp](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/113452367/ce45dcf3-611d-4379-a14a-86bc1ab029ab)

**Comment by Dhananjayshukla1** [comment]
@Akshanshkaushal @dakshsinghrathore I would like to work on this issue, could you please assign this to me?

**Comment by dakshsinghrathore** [comment]
Thanks @Akshanshkaushal for creating the issue will assign it to you, in your PR kindly attach the SS of proposed changes, and mention the issue # as well.

**Comment by Akshanshkaushal** [comment]
Is it okay, if I make PR on 1st as SWOC will start from 1st jan?

**Comment by dakshsinghrathore** [comment]
@Akshanshkaushal 1st Jan will do fine.
