### ISSUE TITLE
BUG: Favicon Icon Is Not Visible

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [dakshsinghrathore/Brighter-Beginnings#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is some sort of Issue with Favicon Icon It Is Not Visible on the webpage

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@Kapileswar-Moharana assigned
