### ISSUE TITLE
BUG: SUDOKU SOLVER IS NOT WORKING

### ISSUE THREAD

**Issue by alphaomega4348** [dakshsinghrathore/Brighter-Beginnings#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On clicking the image of sudoku solver it doesn't redirect to the gaming site whereas other two are redirecting.

https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/117167192/7f91f213-89fb-4641-bb80-1aec23eb9ce7

Please assign me this issue under "SWOC'24"

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by alphaomega4348** [comment]
Please assign me this issue @dakshsinghrathore

**Comment by dakshsinghrathore** [comment]
@alphaomega4348 Thanks for finding out the issue, on clicking the game images of first two games its working fine but the third one i.e Sudoku it isn't redirecting to the game as expected. assigning it to you kindly fix it 
HAPPY CODING !
