### ISSUE TITLE
Feat:Adding Dropdown effect on profile logo.

### ISSUE THREAD

**Issue by Ishaparte** [dakshsinghrathore/Brighter-Beginnings#36]
### Describe the feature

Adding dropdown effect to the profile logo for user to navigate on their profile. @dakshsinghrathore I want to work on this issue can you please assign it to me.

### Add ScreenShots

![swoc1](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/113294672/f8d507b1-4af9-44ff-991f-f4d5237789d7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Ishaparte** [comment]
@dakshsinghrathore please assign me this issue

**Comment by dakshsinghrathore** [comment]
Assigning it to you, make sure it is responsive @Ishaparte also do drop a star on this repo
HAPPY CODING !

**Comment by Ishaparte** [comment]
Yes. Thank you!

**Comment by NaveenChandraAdhikari** [comment]
@dakshsinghrathore can i work upon this issue

**Comment by dakshsinghrathore** [comment]
@NaveenChandraAdhikari Sure!

**Comment by Ishaparte** [comment]
@dakshsinghrathore I am working on this issue.

**Comment by dakshsinghrathore** [comment]
@Ishaparte his/her PR will be merged, whoever resolves this issue first, 2 weeks is ample amount of time to work on it, so need to close this issue ASAP.

**Comment by Ishaparte** [comment]
@dakshsinghrathore  It is done I will create a pull request by today.

**Comment by Shaba1406** [comment]
@Ishaparte please create the PR

**Comment by Ishaparte** [comment]
I have created and it is merged.
