### ISSUE TITLE
BUG: Nav Bar in mobile view overlaps with Login Button

### ISSUE THREAD

**Issue by dhruvdy** [dakshsinghrathore/Brighter-Beginnings#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Nav Bar in mobile view overlaps with Login and Register button. When transition from small screen to large screen mobile view Nav Bar remains open.

![BugFixed](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/72575065/52a22c8a-a13f-40b1-b37b-93e4df959317)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@dhruvdy assigning it to you✅, do drop a star on this repo 🫱🏼‍🫲🏼
