### ISSUE TITLE
BUG: Underline is not responsive in menu items

### ISSUE THREAD

**Issue by vishal-bhangare** [dakshsinghrathore/Brighter-Beginnings#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Underline in menu items is not responsive in small screen sizes, it goes beyond the width of menu item.
![brighterBeginnings-issue](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/61643919/7247e10f-feda-453d-8ab8-dde5ecbe04f3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by SharmaDhruv2511** [comment]
Hey I want to work on this can you please assign it me? @vishal-bhangare

**Comment by dakshsinghrathore** [comment]
@vishal-bhangare assigned
