### ISSUE TITLE
Adding a better navbar in mobile view

### ISSUE THREAD

**Issue by Akshanshkaushal** [dakshsinghrathore/Brighter-Beginnings#4]
Recognized an improvement , I suggest enhancing the visual of navigation bar in mobile view , currently it seems to be a dull one. I am enthusiastic about addressing and resolving this matter and would appreciate the opportunity to be assigned this task under the SWOC-24 initiative.
![navchange](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/113452367/aa0ba257-333d-438c-9bec-f167a2b146f3)

**Comment by Dhananjayshukla1** [comment]
@Akshanshkaushal @dakshsinghrathore  could you please assign this issue to me?

**Comment by Anubhab-03** [comment]
Shall be able to improvise the navbar design in mobile view. Please assign this to me under SWOC'24

**Comment by dhruvdy** [comment]
@dakshsinghrathore can you please assign this issue to me
