### ISSUE TITLE
Feat: Updating the Footer Section

### ISSUE THREAD

**Issue by Shaba1406** [dakshsinghrathore/Brighter-Beginnings#44]
### Describe the feature

Currently the footer page is so simple.I want SWOC contributors to come up with a possible designs for the footer like adding a hover effects on the social media icon and most attractive designs will get it.
happy coding !

### Add ScreenShots

![Screenshot_20240103_224852](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/97939567/07273f06-9c0b-4099-8905-8ec3ab98141d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by shera-bhai** [comment]
Hey @dakshsinghrathore 👋 

I would like to take up on this issue and enhance the footer section of the project!

Best Regards,
**Shera Bhai**

**Comment by GauriGA** [comment]
@dakshsinghrathore Can you assign me this issue?

**Comment by Shaba1406** [comment]
Do you still want to work on this issue ??

**Comment by GauriGA** [comment]
@Shaba1406 Yes, I will still like to work on this issue

**Comment by Shaba1406** [comment]
Okay assigning to you 👍🏻 Good luck

**Comment by Shaba1406** [comment]
Don't forget to Star the Repo ⭐ @GauriGA

**Comment by dakshsinghrathore** [comment]
@GauriGA any updates ??

**Comment by GauriGA** [comment]
@dakshsinghrathore I have made the changes to it. I added the color of the hover effect on the social media icons and the content in the footer. Is there anything else you would like me to do?

**Comment by GauriGA** [comment]
@dakshsinghrathore Update index.html #80
This is the issue I solved. What more changes would you like me to do?

**Comment by dakshsinghrathore** [comment]
@GauriGA all good, thanks for contributing.
