### ISSUE TITLE
Feat: Creating the About page

### ISSUE THREAD

**Issue by bhavya-anand19** [dakshsinghrathore/Brighter-Beginnings#45]
### Describe the feature

Would like to create the about page for the website

### Add ScreenShots

![Screenshot (173)](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/133582773/a6004b7d-4ae9-4c5c-91c2-a0f84942dd46)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@bhavya-anand19 be as creative as possible and based on that will assign the level of easy medium or hard, also kindly attach the SS of created page in the PR. assigning it to you, do drop a star on this repo

**Comment by bhavya-anand19** [comment]
Sure

**Comment by bhavya-anand19** [comment]
@dakshsinghrathore I have created a PR. Kindly have a look
