### ISSUE TITLE
Feat: Improved homepage 

### ISSUE THREAD

**Issue by Yatin12527** [dakshsinghrathore/Brighter-Beginnings#48]
### Describe the feature

I Think the homepage looks too plain and I can keep the color theme same and edit it to make it look better. I previously edited the register page for the same site so that's my reference work!

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/2afc7b6b-71f6-4bf9-b633-1d9505cbcfcf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@Yatin12527 assigned, if possible do try to add graphics related to the topic.
HAPPY CODING !

**Comment by Yatin12527** [comment]
@dakshsinghrathore sure Ima give it a try
