### ISSUE TITLE
Feat: Change Twitter logo to X

### ISSUE THREAD

**Issue by blindaks** [dakshsinghrathore/Brighter-Beginnings#51]
### Describe the feature

We can change the Twitter logo to X in the footer section.

### Add ScreenShots

<img width="150" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/128223364/d308ab2b-4fe0-4703-b8f4-f9e5f732d050">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@blindaks assigned, do drop a star on this repo 
HAPPY CODING !

**Comment by Shaba1406** [comment]
@blindaks Hey, how is the work going on ? What's the update ?

**Comment by dakshsinghrathore** [comment]
anyone who wants to resolve this, create a PR soon

**Comment by trs-web** [comment]
I would like to work on this!

**Comment by siwamsingh** [comment]
Completed !!
