### ISSUE TITLE
BUG: Text not visible

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/Brighter-Beginnings#53]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As you can see the blur upon scrolling the landing page, I want contributors to update the text-color which suits here.

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/698cff2c-4bbe-4d87-9de3-b1ee77aeb122)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by IamSudhir-Kumar** [comment]
Hey! @dakshsinghrathore ,
can you assign me this issue!! I am contributor in SWOC24

**Comment by dakshsinghrathore** [comment]
@IamSudhir-Kumar Sure, assigned, kindly drop a star on this repo 
HAPPY CODING
