### ISSUE TITLE
Feat: Update the lorem text

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/Brighter-Beginnings#54]
### Describe the feature

Currently in the registration page, description offers only lorem, update it with apt text.

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/23f22e71-9ebb-4a22-bf74-551cc12df8d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by thewoodchadli** [comment]
Hey there, this looks fairly simple. Can I have this assigned to me? thanks :)

**Comment by Prutha-Upadhyay** [comment]
I would like to work on this issue!!Can you assign me this issue under SWOC?

**Comment by Shreyas-SAS** [comment]
3rd in line, could put up a PR if assigned the issue asap.

A suggestion to whoever takes it up. It could be great if we could introduce the project in 1 line and then answer why us in 2nd line. It is general notion that most people don't go through the registration at stop at it leaving it for sometime later.

**Comment by dakshsinghrathore** [comment]
@thewoodchadli Assigning it to you, make it short and simple yet effective. Do star the repo
HAPPY CODING !
