### ISSUE TITLE
Feat: Student Contribution Portal/Form

### ISSUE THREAD

**Issue by Shreyas-SAS** [dakshsinghrathore/Brighter-Beginnings#59]
### Describe the feature

Many times if not all, students learn from multiple sources and combine together precise notes that covers good from all sources. What I wish to implement is a form/portal that could be used to receive such handout notes from beginner students using the website who most likely would not be knowledgable enough about Github to create an issue or a pull request to contribute that.

For simplicity and more comfort of students I was thinking about a google form linked to your email ID if you are okay rather than creating a full web based form from scratch. I believe that most people would have already used google form before and would be much more comfortable using that.

Kindly share your views on this @dakshsinghrathore 

### Add ScreenShots

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/96542494/9c13ce71-2186-4938-b14b-ee554b4d5d74)
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/96542494/48c146f6-306e-40ba-a75e-709561c06d28)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Shreyas-SAS** [comment]
[Here](https://docs.google.com/forms/d/e/1FAIpQLSf2z7IbbamHnNyEJJ2g1x5umSMK6_isHgUFLjmJeBhJP65UnQ/viewform) is the sample form link, would create a proper detailed version with all details once approved and assigned with the issue.

Thanks,
Shreyas

**Comment by dakshsinghrathore** [comment]
@Shreyas-SAS assigned, where do you plan to incorporate this form ?

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS assigned, where do you plan to incorporate this form ?

I thought that a new anchor link behind a button saying "contribute" at the footer section would be good place. Do you have a better place in mind? I am all open for suggestions about placement.

**Comment by Shreyas-SAS** [comment]
@dakshsinghrathore please share your email ID for collecting the responses of the form.

Thanks.

**Comment by Shreyas-SAS** [comment]
@dakshsinghrathore can I use this mail? - dsr1729@gmail.com to share the responses to you
