### ISSUE TITLE
BUG: update year dynamically

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/Brighter-Beginnings#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In all the modules i.e m1, m2 & m3 the footer has copyright year hardcoded, kindly update them to the current year using JS
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/cd05f94a-1e2a-4177-bdf6-f451fb15f4c6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by Komal-Rauniyar** [comment]
@dakshsinghrathore assign this issue with ms

**Comment by harshsinghcs** [comment]
@dakshsinghrathore i also want to work in this issue 
I'll help you
