### ISSUE TITLE
Feat: UI update

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/Brighter-Beginnings#66]
### Describe the feature

The hamburger icon fails to display a cross symbol when clicked on.

### Add ScreenShots

Currently ⬇️

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/7cdbe144-d3ac-42f7-8b05-0a230d5f930f)

Change wanted ⬇️

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/61370ae8-9f91-417b-b05e-777511757a5e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by saurav2208** [comment]
@dakshsinghrathore I would like to work on this issue. Please assign me.

**Comment by dakshsinghrathore** [comment]
@saurav2208 assigned, kindly drop a star on this repo !
