### ISSUE TITLE
BUG: There is no title logo

### ISSUE THREAD

**Issue by AbhineshJha** [dakshsinghrathore/Brighter-Beginnings#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-01-07 004428](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/142514166/45a40bb4-cbe3-47aa-82d2-d2bc82a939fd)

Wanna add the logo in title bar ! Can u assign me with this issue ?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by siwamsingh** [comment]
@AbhineshJha you can proceed with this issue but remember that the logo should be circular and not a square or rectangle.

**Comment by AbhineshJha** [comment]
sure  ! can u add SWOC label ?
