### ISSUE TITLE
Feat: Adding a captivating tagline for the Registration Page

### ISSUE THREAD

**Issue by SurajPratap10** [dakshsinghrathore/Brighter-Beginnings#79]
### Describe the feature

- Removed the default Lorem Ipsum text
- Enhance user engagement and promote inclusivity on the website with this latest feature update – a captivating tagline for the registration page.

### Add ScreenShots

- Before:
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92919173/6090af1c-1303-4d59-9bc8-2b954a897917)

- After:
![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/92919173/30bc414b-b8ea-4c09-855a-b4d3822ec6fc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
@SurajPratap10 assigned ✅, kindly drop a star on this repo

**Comment by SurajPratap10** [comment]
> @SurajPratap10 assigned ✅, kindly drop a star on this repo

SWOC label?
