### ISSUE TITLE
BUG: In the footer, dynamically generate the copyright year instead of hardcoding it.

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/Brighter-Beginnings#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/115932772/23c4e586-3f91-4a42-9f0d-61588343349f)

**Simple JS implementation is required to achieve this**

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a SWOC24 contributor
- [ ] I want to work on this issue

**Comment by Dwayne-B** [comment]
Hello could you please assign this issue to me thank you 😄 👍

**Comment by iSubhamMani** [comment]
Hi! I would like to work on this issue. Can you please assign it to me ?

**Comment by dakshsinghrathore** [comment]
Hey @iSubhamMani thanks for your response, but we maintainers have been instructed to assign the issues on first come first serve basis, will assign this particular issue to @Dwayne-B , you can explore other issues which I will create soon.
Thanks for your patience.

**Comment by iSubhamMani** [comment]
Hey @dakshsinghrathore since this issue has not been resolved yet can i work on this ?

**Comment by dakshsinghrathore** [comment]
@iSubhamMani Sure assigning it to you✅, do drop a star on this repo 🫱🏼‍🫲🏼
