### ISSUE TITLE
Feat: Adding Link to The Social icons instead of website opening in a new tab

### ISSUE THREAD

**Issue by Devanshu53** [dakshsinghrathore/Brighter-Beginnings#81]
### Describe the feature

i want to add different links in each icon given on page. For example like if we click on github icon then it opens your repo in a new tab. That will help users to get more known about the project admin or owner.please give this issue sir to me! Thank you.

### Add ScreenShots

<img width="960" alt="Screenshot 2024-01-07 130932" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/138321835/19cef427-62ee-4e7e-bd88-27075a3deb7e">
as i go to any of the link given below in the social icons again the webpage opens in a new tab 
<img width="960" alt="Screenshot 2024-01-07 131312" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/138321835/8ee0f523-b77b-4f55-ac23-6f098a63ad74">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by siwamsingh** [comment]
Sorry @Devanshu53 but this website doesn't have any social presence now. Feel free to choose from any other issue.
