### ISSUE TITLE
BUG: Make the footer for getstart.html page

### ISSUE THREAD

**Issue by Parmesh119** [dakshsinghrathore/Brighter-Beginnings#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I am clicked on get start button in that page the footer section is not there.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Parmesh119** [comment]
I am working on this issue.

**Comment by dakshsinghrathore** [comment]
@Parmesh119 not required for now, kindly work on some other issues
