### ISSUE TITLE
Feat: Add the global discussion section

### ISSUE THREAD

**Issue by Parmesh119** [dakshsinghrathore/Brighter-Beginnings#84]
### Describe the feature

Now in days, every website has the global discussion section or global community section. If the particular user wants to join.

### Add ScreenShots

![Screenshot from 2024-01-08 11-33-35](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/101285245/a49e758b-6300-41c2-8f8f-a0e012292fc0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by siwamsingh** [comment]
Well we don't have any plans on adding a global discuss section now . Feel free to choose any other issue 😊.
