### ISSUE TITLE
BUG:The Copyright Year is Still 2022 in other pages

### ISSUE THREAD

**Issue by shakti177** [dakshsinghrathore/Brighter-Beginnings#88]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Copyright Year of other pages is still 2022.

<img width="1253" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/57393413/386fa18f-32d1-4185-ac3f-18e8d77c18e5">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by siwamsingh** [comment]
@shakti177 use the method used in main page . I am assigning this issue to you .
