### ISSUE TITLE
Navbar is not responsive and not fixed

### ISSUE THREAD

**Issue by Nandini80** [dakshsinghrathore/Brighter-Beginnings#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar is not fixed due to which it is overlapping with all the other content
<img width="892" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/121488571/bf90986a-c561-4938-b0a7-3c8b296744d3">

also these tabs in the navbar are not responsive at all.
<img width="537" alt="image" src="https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/121488571/338b54aa-b862-42fa-b7eb-e1785a6c79c3">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Yatin12527** [comment]
I can fix that Blur header and replace it with an appropriate solid header which does not overlap with content.

**Comment by dakshsinghrathore** [comment]
@Nandini80 Thanks for pointing out the issue, but it is a feature which we have kept it intentionally, so it will be as it is.
Kindly explore other issues, closing this one for now. Also the pages are responsive, do double check it.
Happy Coding !
