### ISSUE TITLE
BUG: update  old twitter logo to new one 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [dakshsinghrathore/Brighter-Beginnings#94]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot from 2024-01-12 03-15-49](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/44281971/80e7ea3a-3e6d-4a08-a988-7c5429c7bdcd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by Paarisha1** [comment]
can i contribute in this under swoc

**Comment by dakshsinghrathore** [comment]
@Paarisha1 Sure, kindly drop a star on this repo before starting to fix the issue , assigning it to you !
HAPPY CODING !
