### ISSUE TITLE
Feat: Add more games like puzzles 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [dakshsinghrathore/Brighter-Beginnings#95]
### Describe the feature

want to add more games like puzzles for users 

### Add ScreenShots

![Screenshot from 2024-01-12 03-23-32](https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/44281971/eb9f8860-25bb-4d82-b1fd-30788a1b026b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a SWOC24 contributor
- [X] I want to work on this issue

**Comment by dakshsinghrathore** [comment]
Assigned this issue to @NaveenChandraAdhikari kindly drop a star on this repo 
HAPPY CODING !

**Comment by NaveenChandraAdhikari** [comment]
your images are uploaded on amazon s3 .So how would I update the images? can i make my own img folder their

**Comment by dakshsinghrathore** [comment]
kindly use cdn link instead !

**Comment by NaveenChandraAdhikari** [comment]
Ok
